server:
  port: 9002

spring:
  application:
    name: emart-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:127.0.0.1}:${DB_PORT:3306}/${DB_SCHEMA:user_db}
    username: ${DB_USERNAME:user_db}
    password: ${DB_PASSWORD:User123}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: 0
    password: ${REDIS_PASSWORD:Redis123}

jwt:
  secret: emart
  expiration: 18000000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka/}