server:
  port: 9002

spring:
  application:
    name: emart-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_db
    username: user_db
    password: User123
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: Redis123

jwt:
  secret: emart
  expiration: 18000000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka/}